export interface ColumnMeta {
  key: string;        // nombre real de la columna en BD
  label: string;      // nombre legible para el usuario
  isObservado: boolean;
  isForeignKey: boolean;
}

export const COLUMN_LABELS: Record<string, ColumnMeta> = {
  id:                                   { key: 'id',                                   label: 'ID',                                    isObservado: false, isForeignKey: false },
  cliente_id:                           { key: 'cliente_id',                           label: 'Cliente',                               isObservado: false, isForeignKey: true  },
  gestion_id:                           { key: 'gestion_id',                           label: 'Gestión',                               isObservado: false, isForeignKey: true  },
  region_id:                            { key: 'region_id',                            label: 'Región',                                isObservado: false, isForeignKey: true  },
  liquidador_id:                        { key: 'liquidador_id',                        label: 'Liquidador',                            isObservado: false, isForeignKey: true  },
  revisor_tributos_id:                  { key: 'revisor_tributos_id',                  label: 'Revisor Tributos',                      isObservado: false, isForeignKey: true  },
  gestor_id:                            { key: 'gestor_id',                            label: 'Gestor',                                isObservado: false, isForeignKey: true  },
  liquidador_extra:                     { key: 'liquidador_extra',                     label: 'Liquidador Extra',                      isObservado: false, isForeignKey: false },
  tipo:                                 { key: 'tipo',                                 label: 'Tipo',                                  isObservado: false, isForeignKey: false },
  interno:                              { key: 'interno',                              label: 'Interno',                               isObservado: false, isForeignKey: false },
  internoTexto:                         { key: 'internoTexto',                         label: 'Interno Texto',                         isObservado: false, isForeignKey: false },
  paso:                                 { key: 'paso',                                 label: 'Paso',                                  isObservado: false, isForeignKey: false },
  estado:                               { key: 'estado',                               label: 'Estado',                                isObservado: false, isForeignKey: false },
  extra:                                { key: 'extra',                                label: 'Extra',                                 isObservado: false, isForeignKey: false },
  a2_fAceptacion:                       { key: 'a2_fAceptacion',                       label: 'Fecha Aceptación',                      isObservado: false, isForeignKey: false },
  a9_plazo:                             { key: 'a9_plazo',                             label: 'Plazo',                                 isObservado: false, isForeignKey: false },
  proveedor:                            { key: 'proveedor',                            label: 'Proveedor',                             isObservado: false, isForeignKey: false },
  pedido:                               { key: 'pedido',                               label: 'Pedido',                                isObservado: false, isForeignKey: false },
  factura:                              { key: 'factura',                              label: 'Factura',                               isObservado: false, isForeignKey: false },
  fechaFactura:                         { key: 'fechaFactura',                         label: 'Fecha Factura',                         isObservado: false, isForeignKey: false },
  descripcion:                          { key: 'descripcion',                          label: 'Descripción',                           isObservado: false, isForeignKey: false },
  observaciones:                        { key: 'observaciones',                        label: 'Observaciones',                         isObservado: false, isForeignKey: false },
  observaciones_ob:                     { key: 'observaciones_ob',                     label: 'Observaciones (Observado)',              isObservado: true,  isForeignKey: false },
  tipoDespacho:                         { key: 'tipoDespacho',                         label: 'Tipo Despacho',                         isObservado: false, isForeignKey: false },
  regimen:                              { key: 'regimen',                              label: 'Régimen',                               isObservado: false, isForeignKey: false },
  urgencia:                             { key: 'urgencia',                             label: 'Urgencia',                              isObservado: false, isForeignKey: false },
  documentoDAM:                         { key: 'documentoDAM',                         label: 'Documento DAM',                         isObservado: false, isForeignKey: false },
  DAM:                                  { key: 'DAM',                                  label: 'DAM',                                   isObservado: false, isForeignKey: false },
  fechaDAM:                             { key: 'fechaDAM',                             label: 'Fecha DAM',                             isObservado: false, isForeignKey: false },
  parteRecepcion:                       { key: 'parteRecepcion',                       label: 'Parte Recepción',                       isObservado: false, isForeignKey: false },
  observacionDimodex:                   { key: 'observacionDimodex',                   label: 'Observación Dimodex',                   isObservado: false, isForeignKey: false },
  observacionDimodex_ob:                { key: 'observacionDimodex_ob',                label: 'Observación Dimodex (Observado)',        isObservado: true,  isForeignKey: false },
  observacionPartida_ob:                { key: 'observacionPartida_ob',                label: 'Observación Partida (Observado)',        isObservado: true,  isForeignKey: false },
  observacionPartida:                   { key: 'observacionPartida',                   label: 'Observación Partida',                   isObservado: false, isForeignKey: false },
  observacionLiquidacion_ob:            { key: 'observacionLiquidacion_ob',            label: 'Observación Liquidación (Observado)',    isObservado: true,  isForeignKey: false },
  observacionLiquidacion:               { key: 'observacionLiquidacion',               label: 'Observación Liquidación',               isObservado: false, isForeignKey: false },
  observacionDocumentacion_ob:          { key: 'observacionDocumentacion_ob',          label: 'Observación Documentación (Observado)', isObservado: true,  isForeignKey: false },
  observacionDocumentacion:             { key: 'observacionDocumentacion',             label: 'Observación Documentación',             isObservado: false, isForeignKey: false },
  numeroItemsRevisadosTributos:         { key: 'numeroItemsRevisadosTributos',         label: 'Número Items Revisados Tributos',        isObservado: false, isForeignKey: false },
  observacionTributos:                  { key: 'observacionTributos',                  label: 'Observación Tributos',                  isObservado: false, isForeignKey: false },
  observacionTributos_ob:               { key: 'observacionTributos_ob',               label: 'Observación Tributos (Observado)',       isObservado: true,  isForeignKey: false },
  paginaInformacionRevision:            { key: 'paginaInformacionRevision',            label: 'Página Información Revisión',           isObservado: false, isForeignKey: false },
  paginaInformacionRevision_ob:         { key: 'paginaInformacionRevision_ob',         label: 'Página Información Revisión (Observado)',isObservado: true,  isForeignKey: false },
  paginaDocumentosRevision_ob:          { key: 'paginaDocumentosRevision_ob',          label: 'Página Documentos Revisión (Observado)',  isObservado: true,  isForeignKey: false },
  paginaDocumentosRevision:             { key: 'paginaDocumentosRevision',             label: 'Página Documentos Revisión',            isObservado: false, isForeignKey: false },
  dimodex:                              { key: 'dimodex',                              label: 'Dimodex',                               isObservado: false, isForeignKey: false },
  pagaCliente:                          { key: 'pagaCliente',                          label: 'Paga Cliente',                          isObservado: false, isForeignKey: false },
  dimodexCorregido:                     { key: 'dimodexCorregido',                     label: 'Dimodex Corregido',                     isObservado: false, isForeignKey: false },
  informacionCorregido:                 { key: 'informacionCorregido',                 label: 'Información Corregido',                 isObservado: false, isForeignKey: false },
  documentosCorregido:                  { key: 'documentosCorregido',                  label: 'Documentos Corregido',                  isObservado: false, isForeignKey: false },
  archivoDIM:                           { key: 'archivoDIM',                           label: 'Archivo DIM',                           isObservado: false, isForeignKey: false },
  archivoDIMReg:                        { key: 'archivoDIMReg',                        label: 'Archivo DIM Reg',                       isObservado: false, isForeignKey: false },
  archivoDEX:                           { key: 'archivoDEX',                           label: 'Archivo DEX',                           isObservado: false, isForeignKey: false },
  observacionValidacion:                { key: 'observacionValidacion',                label: 'Observación Validación',                isObservado: false, isForeignKey: false },
  observacionValidacion_ob:             { key: 'observacionValidacion_ob',             label: 'Observación Validación (Observado)',     isObservado: true,  isForeignKey: false },
  pago_formulario_digital:              { key: 'pago_formulario_digital',              label: 'Pago Formulario Digital',               isObservado: false, isForeignKey: false },
  g5_totalTributos:                     { key: 'g5_totalTributos',                     label: 'Total Tributos',                        isObservado: false, isForeignKey: false },
  a1_numeroDeclaracion:                 { key: 'a1_numeroDeclaracion',                 label: 'Número Declaración',                    isObservado: false, isForeignKey: false },
  a3_numeroReferencia:                  { key: 'a3_numeroReferencia',                  label: 'Número Referencia',                     isObservado: false, isForeignKey: false },
  a4_aduanaDespacho:                    { key: 'a4_aduanaDespacho',                    label: 'Aduana Despacho',                       isObservado: false, isForeignKey: false },
  reciboPago:                           { key: 'reciboPago',                           label: 'Recibo Pago',                           isObservado: false, isForeignKey: false },
  canalColor:                           { key: 'canalColor',                           label: 'Canal Color',                           isObservado: false, isForeignKey: false },
  observacionContravenciones:           { key: 'observacionContravenciones',           label: 'Observación Contravenciones',           isObservado: false, isForeignKey: false },
  reciboEntrega:                        { key: 'reciboEntrega',                        label: 'Recibo Entrega',                        isObservado: false, isForeignKey: false },
  otrosGastos:                          { key: 'otrosGastos',                          label: 'Otros Gastos',                          isObservado: false, isForeignKey: false },
  observacionDespachoAduana:            { key: 'observacionDespachoAduana',            label: 'Observación Despacho Aduana',           isObservado: false, isForeignKey: false },
  facturaVilaseca:                      { key: 'facturaVilaseca',                      label: 'Factura Vilaseca',                      isObservado: false, isForeignKey: false },
  numeroFacturaVilaseca:                { key: 'numeroFacturaVilaseca',                label: 'Número Factura Vilaseca',               isObservado: false, isForeignKey: false },
  numeroPlanillaVilaseca:               { key: 'numeroPlanillaVilaseca',               label: 'Número Planilla Vilaseca',              isObservado: false, isForeignKey: false },
  numeroNotaContable:                   { key: 'numeroNotaContable',                   label: 'Número Nota Contable',                  isObservado: false, isForeignKey: false },
  notaContable:                         { key: 'notaContable',                         label: 'Nota Contable',                         isObservado: false, isForeignKey: false },
  observacionFacturacion:               { key: 'observacionFacturacion',               label: 'Observación Facturación',               isObservado: false, isForeignKey: false },
  observacionDespachoAduanaLiq:         { key: 'observacionDespachoAduanaLiq',         label: 'Observación Despacho Aduana Liq',       isObservado: false, isForeignKey: false },
  observacionDespachoAduanaLiq_ob:      { key: 'observacionDespachoAduanaLiq_ob',      label: 'Observación Despacho Aduana Liq (Observado)', isObservado: true, isForeignKey: false },
  observacionCompletarDoc:              { key: 'observacionCompletarDoc',              label: 'Observación Completar Doc',             isObservado: false, isForeignKey: false },
  observacionCompletarDoc_ob:           { key: 'observacionCompletarDoc_ob',           label: 'Observación Completar Doc (Observado)', isObservado: true,  isForeignKey: false },
  a10_numeroDocAsociado:                { key: 'a10_numeroDocAsociado',                label: 'Número Doc Asociado',                   isObservado: false, isForeignKey: false },
  b1_razonSocial:                       { key: 'b1_razonSocial',                       label: 'Razón Social',                          isObservado: false, isForeignKey: false },
  f2_totalNumeroItems:                  { key: 'f2_totalNumeroItems',                  label: 'Total Número Items',                    isObservado: false, isForeignKey: false },
  f6_totalValorFOB:                     { key: 'f6_totalValorFOB',                     label: 'Total Valor FOB',                       isObservado: false, isForeignKey: false },
  f10_totalValorCIFAduana:              { key: 'f10_totalValorCIFAduana',              label: 'Total Valor CIF Aduana',                isObservado: false, isForeignKey: false },
  g1_tributosDeterminadosGA:            { key: 'g1_tributosDeterminadosGA',            label: 'Tributos Determinados GA',              isObservado: false, isForeignKey: false },
  g2_tributosDeterminadosIVA:           { key: 'g2_tributosDeterminadosIVA',           label: 'Tributos Determinados IVA',             isObservado: false, isForeignKey: false },
  g3_tributosDeterminadosICED:          { key: 'g3_tributosDeterminadosICED',          label: 'Tributos Determinados ICED',            isObservado: false, isForeignKey: false },
  g4_tributosDeterminadosICE:           { key: 'g4_tributosDeterminadosICE',           label: 'Tributos Determinados ICE',             isObservado: false, isForeignKey: false },
  g5_tributosDeterminadosIEHD:          { key: 'g5_tributosDeterminadosIEHD',          label: 'Tributos Determinados IEHD',            isObservado: false, isForeignKey: false },
  e1_datosProveedor:                    { key: 'e1_datosProveedor',                    label: 'Datos Proveedor',                       isObservado: false, isForeignKey: false },
  e3_numeroFactura:                     { key: 'e3_numeroFactura',                     label: 'Número Factura',                        isObservado: false, isForeignKey: false },
  totalFolios:                          { key: 'totalFolios',                          label: 'Total Folios',                          isObservado: false, isForeignKey: false },
  cantidadOriginales:                   { key: 'cantidadOriginales',                   label: 'Cantidad Originales',                   isObservado: false, isForeignKey: false },
  cantidadFotocopiasLeg:                { key: 'cantidadFotocopiasLeg',                label: 'Cantidad Fotocopias Leg',               isObservado: false, isForeignKey: false },
  cantidadFotocopiasSimple:             { key: 'cantidadFotocopiasSimple',             label: 'Cantidad Fotocopias Simple',            isObservado: false, isForeignKey: false },
  aprobado:                             { key: 'aprobado',                             label: 'Aprobado',                              isObservado: false, isForeignKey: false },
  numeroRegularizacion:                 { key: 'numeroRegularizacion',                 label: 'Número Regularización',                 isObservado: false, isForeignKey: false },
  regularizadoInterno:                  { key: 'regularizadoInterno',                  label: 'Regularizado Interno',                  isObservado: false, isForeignKey: false },
  regularizadoDeclaracion:              { key: 'regularizadoDeclaracion',              label: 'Regularizado Declaración',              isObservado: false, isForeignKey: false },
  factura_bs:                           { key: 'factura_bs',                           label: 'Factura BS',                            isObservado: false, isForeignKey: false },
  planilla_sus:                         { key: 'planilla_sus',                         label: 'Planilla SUS',                          isObservado: false, isForeignKey: false },
  planilla_bs:                          { key: 'planilla_bs',                          label: 'Planilla BS',                           isObservado: false, isForeignKey: false },
  recepcion_id:                         { key: 'recepcion_id',                         label: 'Recepción',                             isObservado: false, isForeignKey: true  },
  revision_id:                          { key: 'revision_id',                          label: 'Revisión',                              isObservado: false, isForeignKey: true  },
  contador_id:                          { key: 'contador_id',                          label: 'Contador',                              isObservado: false, isForeignKey: true  },
  facturacion_id:                       { key: 'facturacion_id',                       label: 'Facturación',                           isObservado: false, isForeignKey: true  },
  archivo_id:                           { key: 'archivo_id',                           label: 'Archivo',                               isObservado: false, isForeignKey: true  },
  observacionAsignacion:                { key: 'observacionAsignacion',                label: 'Observación Asignación',                isObservado: false, isForeignKey: false },
  observacionAsignacion_ob:             { key: 'observacionAsignacion_ob',             label: 'Observación Asignación (Observado)',     isObservado: true,  isForeignKey: false },
  observacionContravenciones_ob:        { key: 'observacionContravenciones_ob',        label: 'Observación Contravenciones (Observado)',isObservado: true,  isForeignKey: false },
  observacionDespachoAduana_ob:         { key: 'observacionDespachoAduana_ob',         label: 'Observación Despacho Aduana (Observado)',isObservado: true,  isForeignKey: false },
  observacionFacturacion_ob:            { key: 'observacionFacturacion_ob',            label: 'Observación Facturación (Observado)',    isObservado: true,  isForeignKey: false },
  urlDrive:                             { key: 'urlDrive',                             label: 'URL Drive',                             isObservado: false, isForeignKey: false },
  observacion_iv:                       { key: 'observacion_iv',                       label: 'Observación IV',                        isObservado: false, isForeignKey: false },
  observacion_iv_ob:                    { key: 'observacion_iv_ob',                    label: 'Observación IV (Observado)',             isObservado: true,  isForeignKey: false },
  planillaVilaseca:                     { key: 'planillaVilaseca',                     label: 'Planilla Vilaseca',                     isObservado: false, isForeignKey: false },
  updated_at:                           { key: 'updated_at',                           label: 'Actualizado',                           isObservado: false, isForeignKey: false },
  created_at:                           { key: 'created_at',                           label: 'Creado',                                isObservado: false, isForeignKey: false },
  a1_parte_recepcion:                   { key: 'a1_parte_recepcion',                   label: 'Parte Recepción',                       isObservado: false, isForeignKey: false },
  a8_data_recepcion:                    { key: 'a8_data_recepcion',                    label: 'Data Recepción',                        isObservado: false, isForeignKey: false },
  verificar:                            { key: 'verificar',                            label: 'Verificar',                             isObservado: false, isForeignKey: false },
  a5_destino:                           { key: 'a5_destino',                           label: 'Destino',                               isObservado: false, isForeignKey: false },
  a6_modalidad_regimen:                 { key: 'a6_modalidad_regimen',                 label: 'Modalidad Régimen',                     isObservado: false, isForeignKey: false },
  a7_modalidad_despacho:                { key: 'a7_modalidad_despacho',                label: 'Modalidad Despacho',                    isObservado: false, isForeignKey: false },
  observacion_vi:                       { key: 'observacion_vi',                       label: 'Observación VI',                        isObservado: false, isForeignKey: false },
  observacion_vi_ob:                    { key: 'observacion_vi_ob',                    label: 'Observación VI (Observado)',             isObservado: true,  isForeignKey: false },
  a5_aduanaDespacho:                    { key: 'a5_aduanaDespacho',                    label: 'Aduana Despacho',                       isObservado: false, isForeignKey: false },
  a_plazo_dimodex:                      { key: 'a_plazo_dimodex',                      label: 'Plazo Dimodex',                         isObservado: false, isForeignKey: false },
  a6_destino:                           { key: 'a6_destino',                           label: 'Destino',                               isObservado: false, isForeignKey: false },
  a7_modalidad_regimen:                 { key: 'a7_modalidad_regimen',                 label: 'Modalidad Régimen',                     isObservado: false, isForeignKey: false },
  a9_tipo_embarque:                     { key: 'a9_tipo_embarque',                     label: 'Tipo Embarque',                         isObservado: false, isForeignKey: false },
  origen:                               { key: 'origen',                               label: 'Origen',                                isObservado: false, isForeignKey: false },
  internoOrigen:                        { key: 'internoOrigen',                        label: 'Interno Origen',                        isObservado: false, isForeignKey: false },
};